@startuml

Package StatisticsAggregate {
    class ProjectStatistics <<Entity>> <<Root>>
    class ProjectCategoryStatistics <<Entity>>
    class FirmCategory3 <<ValueObject>>
    class FirmForecast <<ValueObject>>
    
    ProjectStatistics "1" -- "*" ProjectCategoryStatistics
    ProjectStatistics "1" -- "*" FirmForecast
    ProjectCategoryStatistics "1" -- "*" FirmCategory3
}

Package FirmAggregate {
    class Firm <<Entity>> <<Root>>
    class FirmActivity <<ValueObject>>
    class FirmBalance <<ValueObject>>
    class FirmCategory1 <<ValueObject>>
    class FirmCategory2 <<ValueObject>>
    class FirmTerritory <<ValueObject>>
    
    Firm "1" -- "1" FirmActivity
    Firm "1" -- "*" FirmBalance
    Firm "1" -- "*" FirmCategory1
    Firm "1" -- "*" FirmCategory2
    Firm "1" -- "*" FirmTerritory
}

Package ClientAggregate {
    class Client <<Entity>> <<Root>>
    class ClientContact <<ValueObject>>

    Client "1" -- "*" ClientContact
}

Package ProjectAggregate {
    class Project <<Entity>> <<Root>>
    class ProjectCategory <<ValueObject>>

    Project "1" -- "*" ProjectCategory
}

Package TerritoryAggregate {
    class Territory <<Entity>> <<Root>>
}

Package CategoryGroupAggregate {
    class CategoryGroup <<Entity>> <<Root>>
}

StatisticsAggregate -down-> FirmAggregate
StatisticsAggregate -down-> ProjectAggregate

FirmAggregate -down-> ProjectAggregate
FirmAggregate -down-> ClientAggregate
FirmAggregate -down-> CategoryGroupAggregate
FirmAggregate -down-> TerritoryAggregate

@enduml
