@startuml

package ValidationResultAggregate {
    object Version {
        Version
    }
    
    object ErmState {
        Token
    }

    object ValidationResult {
        OrderId
        PeriodStart
        PeriodEnd
        ProjectId

        MessageType
        MessageParams
        
        Result
    }
    

    Version *-- ValidationResult
    Version *-- ErmState
}

@enduml
