@startuml

package PriceAggregate {
    object Price
    object AdvertisementAmountRestriction
    object PriceAssociatedPosition
    object PriceDeniedPosition
        
    Price *-- PriceAssociatedPosition
    Price *-- PriceDeniedPosition
    Price *-- AdvertisementAmountRestriction
}

package PeriodAggregate {
    object Period
    object OrderPeriod
    object PricePeriod
    
    Period *-- OrderPeriod
    Period *-- PricePeriod
}

package OrderAggregate {
    object Order
    object OrderPosition
    object OrderPrice
    
    Order *-- OrderPosition
    Order *-- OrderPrice
}

package RulesetAggregate <<Singleton>> {
    object Ruleset
    object RulesetAssociatedPosition
    object RulesetDeniedPosition

    Ruleset *-- RulesetAssociatedPosition
    Ruleset *-- RulesetDeniedPosition
}

package PositionAggregate {
    object Position
}

'ссылки на внешние агрегаты

Price o-- PricePeriod
Order o-- OrderPeriod

Price o-- OrderPrice

' Position пропускаем, а то много нагромождений
'Position o-- OrderPosition
'Position o-- AdvertisementAmountRestriction

' чтобы packages на UI располагались вертикально, соединим их невидимыми линиями
AdvertisementAmountRestriction -[hidden]down- RulesetAggregate
AdvertisementAmountRestriction -[hidden]down- PositionAggregate

@enduml
