@startuml

package ValidationResultAggregate {

    object ValidationResult {
        #OrderId
        #OrderTimestamp
        #PeriodStart
        #PeriodEnd
        #MessageType
        
        ProjectId
        IsFailed
        MessageParams
    }
}

@enduml
