@startuml

package ValidationResultAggregate {

    object ValidationResult {
        #OrderId
        #PeriodStart
        #PeriodEnd
        #MessageType
        
        ProjectId
        
        IsFailed
        MessageParams
    }
    
    object HistoryValidationResult {
        OrderVersion
        IsFailed
        MessageParams
    }
    
    ValidationResult *-- HistoryValidationResult
}

@enduml
