@startuml

Package PeriodAggregate {
    abstract Project
    class Period
    Project "1" -left- "*" Period
}

package PositionAggregate {
    class Position
    abstract PositionCategory
    Position "*" -right- "1" PositionCategory
}

package OrderAggregate {
    Order "1" -up- "*" OrderPosition
    Order "1" -right- "*" OrderPrice
    Order "1" -down- "*" OrderPeriod
    OrderPeriod "*" -down- "1" Period
    OrderPosition "*" -up- "1" Position
}

package PriceAggregate {
    abstract MasterPositionGroup
    Price "1" -left- "*" OrderPrice
    Price "1" -down- "*" PricePeriod
    Price "1" -up- "*" MasterPosition
    Price "1" -up- "*" DeniedPosition
    Price "1" -up- "*" AdvertisementAmountRestriction
    PricePeriod "*" -down- "1" Period

    MasterPosition "*" -up- "1" Position
    DeniedPosition "*" -up- "1" Position
    AdvertisementAmountRestriction "*" -up- "1" Position
    
    MasterPosition "*" -- "1" MasterPositionGroup
}

legend right
  Сущности помеченные как абстрактные в конечной реализации 
  могут быть представлены лишь ссылками на них, но отсутствовать как таблицы
endlegend

@enduml
